package manager

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"pocketpanel/api/internal/models"
)

// ServerProperties represents a parsed server.properties file
type ServerProperties struct {
	serverProps map[string]string
}

// DefaultServerProperties returns a map of default server properties
func DefaultServerProperties() map[string]string {
	return map[string]string{
		"server-port":         "25565",
		"server-ip":           "",
		"online-mode":         "true",
		"spawn-protection":     "16",
		"max-players":         "20",
		"level-name":          "world",
		"level-seed":          "",
		"level-type":          "minecraft:normal",
		"enable-query":        "false",
		"query.port":          "25565",
		"enable-rcon":         "false",
		"rcon.password":       "",
		"rcon.port":           "25575",
		"allow-flight":        "false",
		"announce-player-achievements": "true",
		"allow-nether":        "true",
		"enable-command-block": "false",
		"force-gamemode":      "false",
		"hardcore":            "false",
		"minecraft-version":   "",
		"max-build-height":    "256",
		"max-tick-time":       "60000",
		"spawn-animals":       "true",
		"spawn-monsters":      "true",
		"spawn-npcs":          "true",
		"view-distance":       "10",
		"white-list":          "false",
		"generate-structures": "true",
		"generator-settings":  "",
	}
}

// GenerateServerProperties generates a server.properties file for the given server
func GenerateServerProperties(server *models.Server, serverDir string) error {
	// Ensure directory exists
	if err := os.MkdirAll(serverDir, 0755); err != nil {
		return fmt.Errorf("failed to create server directory: %w", err)
	}

	propsPath := filepath.Join(serverDir, "server.properties")
	
	// Start with default properties
	props := DefaultServerProperties()
	
	// Override with server-specific settings
	props["server-port"] = fmt.Sprintf("%d", server.Port)
	props["minecraft-version"] = server.Version

	// Generate the file content
	var builder strings.Builder
	builder.WriteString("# Minecraft server properties\n")
	builder.WriteString("# Generated by PocketPanel\n")
	builder.WriteString(fmt.Sprintf("# Generated for server: %s\n", server.Name))
	builder.WriteString("#\n")
	
	for key, value := range props {
		builder.WriteString(fmt.Sprintf("%s=%s\n", key, value))
	}

	// Write the file
	if err := os.WriteFile(propsPath, []byte(builder.String()), 0644); err != nil {
		return fmt.Errorf("failed to write server.properties: %w", err)
	}

	return nil
}

// AcceptEULA accepts the Mojang EULA by creating eula.txt
func AcceptEULA(serverDir string) error {
	eulaPath := filepath.Join(serverDir, "eula.txt")
	eulaContent := `# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
# Generated by PocketPanel
eula=true
`
	if err := os.WriteFile(eulaPath, []byte(eulaContent), 0644); err != nil {
		return fmt.Errorf("failed to write eula.txt: %w", err)
	}
	return nil
}

// ParseServerProperties parses a server.properties file
func ParseServerProperties(serverDir string) (*ServerProperties, error) {
	propsPath := filepath.Join(serverDir, "server.properties")
	
	data, err := os.ReadFile(propsPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &ServerProperties{serverProps: DefaultServerProperties()}, nil
		}
		return nil, fmt.Errorf("failed to read server.properties: %w", err)
	}

	props := make(map[string]string)
	lines := strings.Split(string(data), "\n")
	
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		
		// Parse key=value
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			props[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
		}
	}

	return &ServerProperties{serverProps: props}, nil
}

// Get returns the value of a property
func (sp *ServerProperties) Get(key string) string {
	return sp.serverProps[key]
}

// Set sets the value of a property
func (sp *ServerProperties) Set(key, value string) {
	sp.serverProps[key] = value
}

// GetInt returns the value of a property as an int
func (sp *ServerProperties) GetInt(key string, defaultVal int) int {
	val, ok := sp.serverProps[key]
	if !ok {
		return defaultVal
	}
	var result int
	fmt.Sscanf(val, "%d", &result)
	return result
}

// GetUint returns the value of a property as a uint
func (sp *ServerProperties) GetUint(key string, defaultVal uint) uint {
	val, ok := sp.serverProps[key]
	if !ok {
		return defaultVal
	}
	var result uint
	fmt.Sscanf(val, "%d", &result)
	return result
}

// GetBool returns the value of a property as a bool
func (sp *ServerProperties) GetBool(key string, defaultVal bool) bool {
	val, ok := sp.serverProps[key]
	if !ok {
		return defaultVal
	}
	return val == "true"
}

// Save writes the server properties to a file
func (sp *ServerProperties) Save(serverDir string) error {
	propsPath := filepath.Join(serverDir, "server.properties")
	
	var builder strings.Builder
	for key, value := range sp.serverProps {
		builder.WriteString(fmt.Sprintf("%s=%s\n", key, value))
	}

	return os.WriteFile(propsPath, []byte(builder.String()), 0644)
}
